name: Makefile CI

on:
  push:
    branches: [ "riscv" ]
  # pull_request:
  #   branches: [ "riscv" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: gregdavill/setup-riscv-gnu-toolchain@v2.0
    - uses: colinaaa/setup-riscv-gnu-toolchain@v1.0.2
      with:
        # optional, see: https://toolchains.bootlin.com/releases_riscv64.html
        release-date: 2020.08-1
    - uses: actions/checkout@v4

    - run: make

    - run: make qemu


    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: xv6-riscv-build-artifacts # artifact name
        path: |
          **/*

    # - name: configure
      # run: ./configure

